--CREATE DATABASE PlanningPoker;
--GO

USE PlanningPoker;
GO

CREATE TABLE Rooms (
    RoomId UNIQUEIDENTIFIER PRIMARY KEY,
    ScrumMasterId UNIQUEIDENTIFIER,
    RoomCode NVARCHAR(50),
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Members (
    MemberId UNIQUEIDENTIFIER PRIMARY KEY,
    RoomId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Rooms(RoomId),
    MemberName NVARCHAR(100)
);

CREATE TABLE Votes (
    VoteId UNIQUEIDENTIFIER PRIMARY KEY,
    RoomId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Rooms(RoomId),
    MemberId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Members(MemberId),
    VoteValue INT,
    VotedAt DATETIME DEFAULT GETDATE()
);

